name: Build and Publish PHP8.2

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      -
          name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
          name: Build and push
          uses: docker/build-push-action@v3
          with:
            context: ./php/laravel/8.2
            file: ./php/laravel/8.2/Dockerfile
            builder: ${{ steps.buildx.outputs.name }}
            push: true
            tags: eamirgh/laravel9-php8.2:latest
